@startuml name
entity Entity {
   * entity_id «PK»
   ---
   name
   birth_date
   gender
   + specie_id «FK»
   + covering_id «FK»
}

entity Covering {
   * covering_id «PK»
   ---
   type
   color
   pattern
}

entity Action {
   * action_id «PK»
   ---
   name
   timestamp
   description
   + place_id «FK»
}

entity Place {
   * place_id «PK»
   ---
   name
   description
}

entity Object {
   * object_id «PK»
   ---
   name
}

entity State {
   * state_id «PK»
   ---
   name
}

entity Specie {
   * specie_id «PK»
   ---
   name
   description
}

Entity::specie_id }|--|| Specie::specie_id
Entity::covering_id }|--|| Covering::covering_id
Entity::entity_id }|--|{ Action::action_id
State }|--|{ Object
Action::place_id }|--|| Place::place_id
Object }|--|{ Action
@enduml