@startuml name

class Command {
   +execute(): void
   +description(): String
}

class Ticket {
   -id: Long;
   -name: String
   -coordinates: Coordinates
   -creationDate: java.time.LocalDateTime
   -price: int
   -type: TicketType
   -event: Event
}
class Coordinates {
   -x: Float
   -y: Float
}
class Event {
   -id: Long
   -name: String
   -description: String
   -eventType: EventType
}
enum TicketType {
   VIP
   USUAL
   BUDGETARY
   CHEAP
}
enum EventType {
   CONCERT
   BASEBALL
   OPERA
}

@enduml