@startuml name
SpecialMove <|-- ShadowBall
SpecialMove <|-- Thunderbolt
SpecialMove <|-- DreamEater
SpecialMove <|-- Bubble
Bubble <|-- BubbleBeam

class BubbleBeam {
    #power: double
    ~BubbleBeam()
    +describe(): string
}

class Bubble {
    #power: double
    #type: Type
    #accuracy: double
    ~Bubble()
    +describe(): string
}

class DreamEater {
    #power: double
    #type: Type
    #accuracy: double
    ~DreamEater()
    +describe(): string
    +checkAccuracy(): boolean
    +applySelfDamage(p: Pokemon, damage: double): void
}

class Thunderbolt {
    #power: double
    #type: Type
    #accuracy: double
    ~Thunderbolt()
    +describe(): string
    +applyOppEffects(p: Pokemon): void
}

class ShadowBall {
    #power: double
    #type: Type
    #accuracy: double
    ~ShadowBall()
    +describe(): string
    +applyOppEffects(p: Pokemon): void
}
@enduml
