@startuml name
Pokemon <|-- Mesprit
Pokemon <|-- Sneasel
Sneasel <|--Weavile
Pokemon <|-- Poliwag
Poliwag <|-- Poliwhirl
Poliwhirl <|-- Politoed

class Mesprit {
    ~Mesprit()
    ~Mesprit(name: string, level: int)
}

class Sneasel {
    ~Sneasel()
    ~Sneasel(name: string, level: int)
}

class Weavile {
    ~Weavile()
    ~Weavile(name: string, level: int)
}

class Poliwag {
    ~Poliwag()
    ~Poliwag(name: string, level: int)
}

class Poliwhirl {
    ~Poliwhirl()
    ~Poliwhirl(name: string, level: int)
}

class Politoed {
    ~Politoed()
    ~Politoed(name: string, level: int)
}
@enduml
